
FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y wget \
    && wget -q "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell

WORKDIR /

COPY ./src/ /PoshJohn/src/
COPY ./scripts/linux/ /PoshJohn/scripts/linux/
COPY ./PowerShellBuildTools/ /PoshJohn/PowerShellBuildTools/
COPY ./test/ /PoshJohn/test/
COPY ./global.json /PoshJohn/global.json

WORKDIR /PoshJohn/scripts

RUN for f in *.sh; do \
    chmod +x "$f"; \
    done

WORKDIR /PoshJohn

ENV SKIP_NATIVE_BUILD=false
RUN pwsh -Command ./PowerShellBuildTools/build.ps1 -Task Build
