<Project>
  <!-- Run native build scripts before publish -->
  <Target Name="PreBuildNativeAssets"
          BeforeTargets="Publish"
          Condition=" '$(SKIP_NATIVE_BUILD_ASSETS)' != 'true' ">
    <!-- Linux -->
    <Exec Command="bash $(ProjectDir)../scripts/linux/build-john.sh"
          Condition=" $([System.OperatingSystem]::IsLinux()) " />
    <Exec Command="bash $(ProjectDir)../scripts/linux/build-pdf2john.sh"
          Condition=" $([System.OperatingSystem]::IsLinux()) " />

    <!-- macOS -->
    <Exec Command="bash $(ProjectDir)../scripts/macos/build-john.sh"
          Condition=" $([System.OperatingSystem]::IsMacOS()) " />
    <Exec Command="bash $(ProjectDir)../scripts/macos/build-pdf2john.sh"
          Condition=" $([System.OperatingSystem]::IsMacOS()) " />

    <!-- Windows -->
    <Exec Command="pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $(ProjectDir)..\scripts\windows\build-john.ps1"
          Condition=" $([System.OperatingSystem]::IsWindows()) " />
    <Exec Command="pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $(ProjectDir)..\scripts\windows\build-pdf2john.ps1"
          Condition=" $([System.OperatingSystem]::IsWindows()) " />
    <Exec Command="pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $(ProjectDir)..\scripts\windows\build-perl.ps1"
          Condition=" $([System.OperatingSystem]::IsWindows()) " />
    <Exec Command="pwsh.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $(ProjectDir)..\scripts\windows\build-repack7z.ps1"
          Condition=" $([System.OperatingSystem]::IsWindows()) " />
  </Target>

  <!-- Copy native assets into publish output -->
  <Target Name="CopyNativeAssets"
          AfterTargets="PreBuildNativeAssets"
          Condition=" '$(SKIP_NATIVE_COPY_ASSETS)' != 'true' ">
    <!-- pdf2john outputs go into PublishDir/pdf2john -->
    <ItemGroup>
      <Pdf2JohnAssets Include="pdf2john/dist/**" />
    </ItemGroup>
    <Copy SourceFiles="@(Pdf2JohnAssets)"
          DestinationFiles="@(Pdf2JohnAssets->'$(PublishDir)pdf2john\%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />

    <!-- john outputs go into PublishDir/john, preserving subdirectories -->
    <ItemGroup>
      <JohnAssets Include="../john/**" />
    </ItemGroup>
    <Copy SourceFiles="@(JohnAssets)"
          DestinationFiles="@(JohnAssets->'$(PublishDir)john\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />

    <!-- 7z2john outputs go into PublishDir/pdf2john -->
    <ItemGroup Condition="$([System.OperatingSystem]::IsWindows())">
      <StrawberryPerlAssets Include="../strawberry-perl/**" />
    </ItemGroup>
    <Copy SourceFiles="@(StrawberryPerlAssets)"
          DestinationFiles="@(StrawberryPerlAssets->'$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />

    <!-- repack7z outputs go into PublishDir/repack7z -->
    <ItemGroup>
      <Bit7zAssets Include="repack7z/build/dist/**" />
    </ItemGroup>
    <Copy SourceFiles="@(Bit7zAssets)"
          DestinationFiles="@(Bit7zAssets->'$(PublishDir)repack7z\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
