name: Test PoshJohn Module

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[github.ref == 'refs/heads/main'] }}

jobs:

  build-john-assets-windows:
    name: Build John Assets (Windows)
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build John
        shell: pwsh
        run: ./scripts/build-john-windows.ps1

      - name: Build pdf2john
        shell: pwsh
        run: ./scripts/build-pdf2john-windows.ps1

      - name: Upload John Assets
        uses: actions/upload-artifact@v4
        with:
          name: john-Windows
          path: ${{ github.workspace }}/john
          if-no-files-found: error

      - name: Upload pdf2john Assets
        uses: actions/upload-artifact@v4
        with:
          name: pdf2john-Windows
          path: ${{ github.workspace }}/src/pdf2john/dist
          if-no-files-found: error

  build-john-assets-linux:
    name: Build John Assets (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build John
        run: |
          chmod +x ./scripts/build-john-linux.sh
          sudo ./scripts/build-john-linux.sh

      - name: Build pdf2john
        run: |
          chmod +x ./scripts/build-pdf2john-linux.sh
          sudo ./scripts/build-pdf2john-linux.sh

      - name: Upload John Assets
        uses: actions/upload-artifact@v4
        with:
          name: john-Linux
          path: ${{ github.workspace }}/john
          if-no-files-found: error

      - name: Upload pdf2john Assets
        uses: actions/upload-artifact@v4
        with:
          name: pdf2john-Linux
          path: ${{ github.workspace }}/src/pdf2john/dist
          if-no-files-found: error

  build-john-assets-macos:
    name: Build John Assets (MacOS)
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build John
        run: |
          chmod +x ./scripts/build-john-macos.sh
          ./scripts/build-john-macos.sh

      - name: Build pdf2john
        run: |
          chmod +x ./scripts/build-pdf2john-macos.sh
          ./scripts/build-pdf2john-macos.sh

      - name: Upload John Assets
        uses: actions/upload-artifact@v4
        with:
          name: john-MacOS
          path: ${{ github.workspace }}/john
          if-no-files-found: error

      - name: Upload pdf2john Assets
        uses: actions/upload-artifact@v4
        with:
          name: pdf2john-MacOS
          path: ${{ github.workspace }}/src/pdf2john/dist
          if-no-files-found: error

  build-module:
    name: Build PowerShell Module
    needs:
      - build-john-assets-windows
      - build-john-assets-linux
      - build-john-assets-macos
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Repo checkout
      pull-requests: write  # Comment on PRs

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build module
        shell: pwsh
        env:
          SKIP_NATIVE_BUILD: true
        run: ./PowerShellBuildTools/build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build

      - name: Capture PowerShell Module
        uses: actions/upload-artifact@v4
        with:
          name: PSModule
          path: out/*.nupkg
          if-no-files-found: error

  test-module:
    name: Test PowerShell Module (${{ matrix.info.name }})
    needs:
      - build-module
    runs-on: ${{ matrix.info.os }}
    permissions:
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        info:
        - name: Windows
          os: windows-latest
        - name: Linux
          os: ubuntu-latest
        - name: MacOS
          os: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore Built PowerShell Module
        uses: actions/download-artifact@v4
        with:
          name: PSModule
          path: out

      - name: Download John Assets
        uses: actions/download-artifact@v4
        with:
          name: john-${{ matrix.info.name }}
          path: john-artifacts/${{ matrix.info.name }}

      - name: Download pdf2john Assets
        uses: actions/download-artifact@v4
        with:
          name: pdf2john-${{ matrix.info.name }}
          path: pdf2john-artifacts/${{ matrix.info.name }}

      - name: Install Built PowerShell Module
        shell: pwsh
        run: |
          # Extract the nupkg
          Import-Module ./PowerShellBuildTools/tools/helper.psm1 -Force
          Expand-Nupkg -ModuleManfifestPath ./src/PoshJohn.psd1 -OutputPath out

          # Find the extracted module directory
          $modulePath = Get-ChildItem -Path out/PoshJohn -Directory | Select-Object -First 1 -ExpandProperty FullName

          # Copy John artifacts to the extracted module
          $johnDestPath = Join-Path $modulePath "john"
          if (Test-Path $johnDestPath) {
              throw "Extracted module should not already contain john artifacts at $johnDestPath"
          }

          New-Item -ItemType Directory -Force -Path $johnDestPath | Out-Null
          Copy-Item -Path john-artifacts/${{ matrix.info.name }}/* -Destination $johnDestPath -Recurse -Force

          # Copy pdf2john artifacts to the extracted module
          $pdf2johnDestPath = Join-Path $modulePath "pdf2john"
          if (Test-Path $pdf2johnDestPath) {
              throw "Extracted module should not already contain pdf2john artifacts at $pdf2johnDestPath"
          }

          New-Item -ItemType Directory -Force -Path $pdf2johnDestPath | Out-Null
          Copy-Item -Path pdf2john-artifacts/${{ matrix.info.name }}/* -Destination $pdf2johnDestPath -Recurse -Force

      - name: Install valgrind
        if: ${{ matrix.info.name == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Run Tests - PowerShell
        shell: pwsh
        run: |
          ./PowerShellBuildTools/build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task TestPackage

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (${{ matrix.info.name }})
          path: ./out/TestResults/Pester.xml
          if-no-files-found: error

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'ubuntu-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'macos-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml

      - name: Publish Test Results (${{ matrix.info.name }})
        if: ${{ matrix.info.os == 'windows-latest' && always() }}
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          check_name: Unit Test Results (${{ matrix.info.name }})
          files: |
            ./out/TestResults/Pester.xml
